repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "playwright install chromium && pytest -q"
        language: system
