# Updated selectors for production landing form
form:
  wrapper: 'div.form-wrapper'
  submit: 'button[type="submit"]'
  name: 'input[name="user_name"]'
  city: 'div.form-wrapper input[name="user_city"]:not(.calculator-list-field-input)'
  phone: 'input[name="user_phone"]'
  gender: 'input[name="user_gender"]'
  age: 'input[name="user_age"]'
  courier: 'input[name="user_courier_type"]'
  policy: '.form-policy-checkbox'
  city_item: 'div.form-wrapper .form-list-item'
  gender_item: '.form-list-item'
  courier_item: '.form-list-item'
  thank_you: '.modal-message-content:visible:has-text("Спасибо"), .modal-message-text:visible:has-text("Спасибо")'
