name: ci
on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install ruff black pytest
      - run: playwright install --with-deps chromium
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
