name: deps-check
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip install -r requirements.lock --upgrade
      - run: playwright install
      - run: pytest
      - run: echo "deps ok"
